### ISSUE TITLE
Additional names that i found

### ISSUE THREAD

**Issue by al6uiz** [emoose/MGSV-QAR-Dictionary-Project#4]
There are some language file set in chunk0.dat package.

/Assets/tpp/pack/ui/lang/lang_default_data_eng
/Assets/tpp/pack/ui/lang/lang_default_data_jpn
/Assets/tpp/pack/ui/lang/lang_default_data_rus
/Assets/tpp/pack/ui/lang/lang_default_data_por
/Assets/tpp/pack/ui/lang/lang_default_data_fre
/Assets/tpp/pack/ui/lang/lang_default_data_ita
/Assets/tpp/pack/ui/lang/lang_default_data_ger
/Assets/tpp/pack/ui/lang/lang_default_data_spa

and there are korean and chinese subtitles in data1.dat package.

I don't know what is the prefix for chinese text set. (was not ChnText)

/Assets/tpp/ui/Subtitles/subp/EngVoice/KorText/child_soldier
/Assets/tpp/ui/Subtitles/subp/EngVoice/KorText/common
/Assets/tpp/ui/Subtitles/subp/EngVoice/KorText/common_str
/Assets/tpp/ui/Subtitles/subp/EngVoice/KorText/enemy_af
/Assets/tpp/ui/Subtitles/subp/EngVoice/KorText/enemy_af_str
/Assets/tpp/ui/Subtitles/subp/EngVoice/KorText/enemy_en
/Assets/tpp/ui/Subtitles/subp/EngVoice/KorText/enemy_en_str
/Assets/tpp/ui/Subtitles/subp/EngVoice/KorText/enemy_ru
/Assets/tpp/ui/Subtitles/subp/EngVoice/KorText/enemy_ru_str
/Assets/tpp/ui/Subtitles/subp/EngVoice/KorText/f30010
/Assets/tpp/ui/Subtitles/subp/EngVoice/KorText/f30020
/Assets/tpp/ui/Subtitles/subp/EngVoice/KorText/f30050
/Assets/tpp/ui/Subtitles/subp/EngVoice/KorText/fob
/Assets/tpp/ui/Subtitles/subp/EngVoice/KorText/h40010
/Assets/tpp/ui/Subtitles/subp/EngVoice/KorText/h40020
/Assets/tpp/ui/Subtitles/subp/EngVoice/KorText/h40050
/Assets/tpp/ui/Subtitles/subp/EngVoice/KorText/radio_cmn_t00
/Assets/tpp/ui/Subtitles/subp/EngVoice/KorText/radio_free
/Assets/tpp/ui/Subtitles/subp/EngVoice/KorText/result
/Assets/tpp/ui/Subtitles/subp/EngVoice/KorText/reward
/Assets/tpp/ui/Subtitles/subp/EngVoice/KorText/s10010
/Assets/tpp/ui/Subtitles/subp/EngVoice/KorText/s10020
/Assets/tpp/ui/Subtitles/subp/EngVoice/KorText/s10030
/Assets/tpp/ui/Subtitles/subp/EngVoice/KorText/s10033
/Assets/tpp/ui/Subtitles/subp/EngVoice/KorText/s10036
/Assets/tpp/ui/Subtitles/subp/EngVoice/KorText/s10040
/Assets/tpp/ui/Subtitles/subp/EngVoice/KorText/s10041
/Assets/tpp/ui/Subtitles/subp/EngVoice/KorText/s10043
/Assets/tpp/ui/Subtitles/subp/EngVoice/KorText/s10044
/Assets/tpp/ui/Subtitles/subp/EngVoice/KorText/s10045
/Assets/tpp/ui/Subtitles/subp/EngVoice/KorText/s10050
/Assets/tpp/ui/Subtitles/subp/EngVoice/KorText/s10052
/Assets/tpp/ui/Subtitles/subp/EngVoice/KorText/s10054
/Assets/tpp/ui/Subtitles/subp/EngVoice/KorText/s10070
/Assets/tpp/ui/Subtitles/subp/EngVoice/KorText/s10080
/Assets/tpp/ui/Subtitles/subp/EngVoice/KorText/s10081
/Assets/tpp/ui/Subtitles/subp/EngVoice/KorText/s10082
/Assets/tpp/ui/Subtitles/subp/EngVoice/KorText/s10085
/Assets/tpp/ui/Subtitles/subp/EngVoice/KorText/s10086
/Assets/tpp/ui/Subtitles/subp/EngVoice/KorText/s10090
/Assets/tpp/ui/Subtitles/subp/EngVoice/KorText/s10091
/Assets/tpp/ui/Subtitles/subp/EngVoice/KorText/s10093
/Assets/tpp/ui/Subtitles/subp/EngVoice/KorText/s10100
/Assets/tpp/ui/Subtitles/subp/EngVoice/KorText/s10110
/Assets/tpp/ui/Subtitles/subp/EngVoice/KorText/s10115
/Assets/tpp/ui/Subtitles/subp/EngVoice/KorText/s10120
/Assets/tpp/ui/Subtitles/subp/EngVoice/KorText/s10121
/Assets/tpp/ui/Subtitles/subp/EngVoice/KorText/s10130
/Assets/tpp/ui/Subtitles/subp/EngVoice/KorText/s10140
/Assets/tpp/ui/Subtitles/subp/EngVoice/KorText/s10150
/Assets/tpp/ui/Subtitles/subp/EngVoice/KorText/s10151
/Assets/tpp/ui/Subtitles/subp/EngVoice/KorText/s10156
/Assets/tpp/ui/Subtitles/subp/EngVoice/KorText/s10171
/Assets/tpp/ui/Subtitles/subp/EngVoice/KorText/s10195
/Assets/tpp/ui/Subtitles/subp/EngVoice/KorText/s10200
/Assets/tpp/ui/Subtitles/subp/EngVoice/KorText/s10211
/Assets/tpp/ui/Subtitles/subp/EngVoice/KorText/s10240
/Assets/tpp/ui/Subtitles/subp/EngVoice/KorText/s10260
/Assets/tpp/ui/Subtitles/subp/EngVoice/KorText/s10280
/Assets/tpp/ui/Subtitles/subp/EngVoice/KorText/tape

**Comment by emoose** [comment]
Thanks for the adds :)

Found the chinese filenames, they were in a ChtText folder. data1.dat is now only missing 2 filenames (fb73c9483333.subp & 3989933189c50.subp), somewhere in between "/Assets/tpp/ui/Subtitles/subp/EngVoice/EngText/common_str" and "/Assets/tpp/ui/Subtitles/subp/EngVoice/EngText/enemy_af"
