### ISSUE TITLE
No more adds until I fix or buy another ps3

### ISSUE THREAD

**Issue by Echelo** [emoose/MGSV-QAR-Dictionary-Project#7]
Unfortunately, I used the remaining life of my ps3 to log those adds.  It is now GLOD/YLOD, it picks which one when it feels like it.

I was only on mission 10, so there is still plenty left to log.

I would have added many more by now, but last commit was right after it died.

Thanks for adding them to your project emoose.

**Comment by emoose** [comment]
Damn that sucks man, thanks for your work so far, hope you can get it fixed eventually (not sure where you are, but in the UK there's a lot of YLOD repair services online which are pretty cheap, might be worth checking if there's anything around you)

I'll try looking into my PC version later, hopefully the memory dump method you used should work with this too (although I still haven't completed it yet... got to mission 30 and sorta lost interest, maybe this can help make me complete it though : P)

Also I was wondering if you still had any of the dumps you looked into, I'm thinking that maybe we could find out which files contain these filenames. Like I said on Xentax I'm pretty sure there's some file encryption we've missed out, if we find out which files are crypted it shouldn't be that hard to find out how the encryption works for them. Once we have them decrypted it'll make it a lot easier than dumping memory for each mission.

**Comment by Echelo** [comment]
Well, I was no longer dumping memory for each mission anymore.  Instead, I hooked the cityhash function.  This way, every time the cityhash function was called, the string being hashed was reported to my debugger's output window.  This yields waaay more results per mission than a memory dump at the start.  I deleted the memory dumps, they were done on xbox360 and were getting quite redundant by mission 20.

I agree, theres probably a btree or lookup table for the strings that we have not found yet.
We could try tracing back from where the string is getting hashed to see how the string is getting generated/decrypted using a debugger.

I'll look around for YLOD repair.

**Comment by emoose** [comment]
Oh right, that's a smarter way to do it. Not sure if I could hook the PC version though (thanks Denuvo :(), although I should be able to with GZ, I figured out the lua crypto thanks to that, maybe we'll get lucky and they'd share the same sort of lookup code too.

Hope you can get it fixed, if it is different to GZ debugging with consoles will probably be the only way to figure it out.

EDIT: Actually I forgot how hard GZ PC is to debug... they use some weird way of anti-debugging, I managed to get around it once by patching stuff at runtime but didn't note down what I did. :(

TPP PC's exe doesn't even mention the constant used in the hash function, so yeah, thanks Denuvo...

AFAIK GZ referenced textures in the model files in cleartext anyway so it probably wouldn't even be that helpful, guess console debugging TPP will be the best way.

EDIT2: Actually I wonder if GZ and TPP maybe share any model files? Might be helpful to find what happened to those cleartext texture refs.

EDIT3: Comparing some of the shared models, seems there are a few changes to the model format, biggest one being the removal of texture filenames... Can't see where they would have put them, there is an extra ~176 bytes added in at one section though (almost exactly half the size of the filename section), maybe an encrypted & compressed version of that filename section?

**Comment by Echelo** [comment]
I'm always on irc.  Join there if you want to chat about it in real time.  We can work together on getting some things solved.

**Comment by Atvaark** [comment]
Doesn't the TPP model format just store the hashes of the required textures now? Maybe @cra0kalo can give us a hint what that new data section is for.

**Comment by Echelo** [comment]
https://facepunch.com/showthread.php?t=1443449&p=49336023&viewfull=1#post49336023

**Comment by emoose** [comment]
> MGS5 uses texture hashes instead of names for model textures aka instead of like "chi1_body0_def_bsm" its 196554adaccbe so yeah reversing the fmdl format etc etc I found they store the texture hashes there so I built a tool
> which you can find in the builders tab that will build a master file for all textures.

Looks like you were right @Atvaark, still strange how PS3 memory dumps contain the full texture filenames though, maybe PS3 fmdls still use filenames like GZ fmdls used to?

**Comment by Echelo** [comment]
It was not ps3 memory dumps, I hooked the cityhash function in a debugger.  I didn't trace back further to see where the strings were being generated from yet, as the ps3 is still broken.

**Comment by emoose** [comment]
Oh yeah of course, wrote that in a bit of hurry and seemed to forget about that :x 

Still, it's calling the cityhash function with those strings so they must be coming from somewhere in the data files.

Hope you can get your PS3 fixed soon, since I don't really think there's much chance of debugging the PC version thanks to this Denuvo BS.

BTW has anyone looked into the PS3 fmdls at all? I had the files a few months ago but can't seem to find them now. (I made a fork of Gzstool that can handle PS3/360 archives btw: https://github.com/emoose/GzsTool/releases - not sure if any other tools support them yet)

**Comment by secaproject** [comment]
Hi emoose. I have some lines to add, where can I put them?

**Comment by Atvaark** [comment]
Hey @secaproject,

you can fork this project via the fork button, edit the dictionary in your own repository and then issue a pull request.
You don't need to use a git client for this. You can do all this on this website.

**Comment by secaproject** [comment]
Thanks @Atvaark for the answer.
Idk if I do it correctly, but I added 86 new filenames.

**Comment by qiurigao** [comment]
I used MGSV_QAR_Tool to decrypt the ps3 version of the dat file, the lua file inside is garbled.
